name: Display hostname

on: [push]

jobs:
  display-hostname:
    runs-on: ubuntu-latest
    steps:
      - name: Run hostname command
        run: hostname

  delivery:
    runs-on: ubuntu-latest
    needs: display-hostname
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sha256:ef54e839ef541993b4e87f25e752f7cf4238fa55f017957c2eb44077083d7a6a .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-website:latest
